version: '2'
services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "127.0.0.1:3308:3307"
    redis:
        image: redis:5-alpine
        command: redis-server
        restart: always
        ports:
            - "6380:6379"
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2-amd64
        env_file:
            - elasticsearch.env
        volumes:
            - ./data/elasticsearch:/usr/share/elasticsearch/data

    kibana:
        image: docker.elastic.co/kibana/kibana:7.9.2
        environment:
            - ELASTICSEARCH_HOST=http://elasticsearch:9200
        ports:
            - 5601:5601

    rabbitmq:
        image: rabbitmq:3.9-management-alpine
        restart: always
        ports:
            - 5673:5672
            - 15673:15672

    app:
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        #  
        # command: bash -c "rm /app/tmp/pids/server.pid && rails s -p 3000 -b 0.0.0.0"
        volumes:
            - ".:/app"
        ports:
            - "3001:3000"
        depends_on:
            - db
            - redis
            - rabbitmq
            - elasticsearch
        links:
            - db
            - redis
            - rabbitmq
            - elasticsearch
        environment:
            DB_USER: root
            DB_NAME: app
            DB_PASSWORD: password
            DB_HOST: db
            REDIS_HOST: redis
            RABBITMQ_HOST: rabbitmq
            ES_HOST: elasticsearch
    chatworker:
        build: .
        command: rake sneakers:run
        volumes:
            - .:/app
        depends_on:
            - db
            - rabbitmq
        restart: always
        environment:
            DB_USER: root
            DB_NAME: app
            DB_PASSWORD: password
            DB_HOST: db
            RABBITMQ_HOST: rabbitmq
            WORKERS: ProcessorChat

    messageworker:
        build: .
        command: rake sneakers:run
        volumes:
            - .:/app
        depends_on:
            - db
            - rabbitmq
        restart: always
        environment:
            DB_USER: root
            DB_NAME: app
            DB_PASSWORD: password
            DB_HOST: db
            RABBITMQ_HOST: rabbitmq
            WORKERS: ProcessorMessage
